# Generated by Django 4.0.3 on 2022-03-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3cat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homemodel',
            old_name='video_id',
            new_name='audio_id',
        ),
    ]
